message("\nConfiguration of package `magmamorse':")
message("        BUILDNAME ...........: ${BUILDNAME}")
message("        SITE ................: ${SITE}")
message(" ")
message("        Compiler: C .........: ${CMAKE_C_COMPILER} (${CMAKE_C_COMPILER_ID})")
message("                version .....: ${COMPILER_C_VERSION}")
if(CMAKE_CXX_COMPILER)
  message("        Compiler: C++ .......: ${CMAKE_CXX_COMPILER} (${CMAKE_CXX_COMPILER_ID})")
  message("                version .....: ${COMPILER_CXX_VERSION}")
endif()
if(CMAKE_Fortran_COMPILER)
  message("        Compiler: Fortran ...: ${CMAKE_Fortran_COMPILER} (${CMAKE_Fortran_COMPILER_ID})")
  message("                version .....: ${COMPILER_Fortran_VERSION}")
endif()
if(MAGMAMORSE_USE_MPI)
  message("        Compiler: MPI .......: ${MPI_C_COMPILER}")
  message("        compiler flags ......: ${MPI_C_COMPILE_FLAGS}")
endif()
message("        Linker: .............: ${CMAKE_LINKER}")
message(" ")
message("        Build type ..........: ${CMAKE_BUILD_TYPE}")
message("        CFlags ..............: ${CMAKE_C_FLAGS}")
message("        CXXFlags ............: ${CMAKE_CXX_FLAGS}")
message("        LDFlags .............: ${CMAKE_C_LINK_FLAGS}")
message(" ")
message("        Implementation paradigm")
message("        CUDA ................: ${MAGMAMORSE_USE_CUDA}")
message("        MPI .................: ${MAGMAMORSE_USE_MPI}")
message(" ")
message("        Runtime specific")
message("        QUARK ...............: ${MAGMAMORSE_SCHED_QUARK}")
message("        StarPU ..............: ${MAGMAMORSE_SCHED_STARPU}")
message("        FxT .................: ${MAGMAMORSE_USE_FXT}")
message(" ")
message("        Kernels specific")
message("        BLAS ................: ${BLA_VENDOR}")
message("        MAGMA ...............: ${MAGMAMORSE_USE_MAGMA}")
message(" ")
message("        Simulation mode .....: ${MAGMAMORSE_SIMULATION}")
message(" ")
message("        Executables to build")
message("        testing ..............: ${MAGMAMORSE_ENABLE_TESTING}")
message("        timing ...............: ${MAGMAMORSE_ENABLE_TIMING}")
message(" ")
message("        Magmamorse dependencies :")
foreach (_dep ${MAGMAMORSE_DEP})
    message("                                  ${_dep}")
endforeach ()
message(" ")
message("        INSTALL_PREFIX ......: ${CMAKE_INSTALL_PREFIX}")
