---
.build_script_linux:
  stage: build
  tags: ["docker", "large"]
  extends: .only-master-mr
  script:
    - bash .gitlab/build.sh | tee ${LOGNAME}.log
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    expire_in: 180 minutes
    untracked: true

build_seq:
  extends: .build_script_linux
  variables:
    SYSTEM: linux
    VERSION: seq
    LOGNAME: "pastix-build-${SYSTEM}-${VERSION}"

build_mpi:
  extends: .build_script_linux
  variables:
    SYSTEM: linux
    VERSION: mpi
    LOGNAME: "pastix-build-${SYSTEM}-${VERSION}"

.build_script_macosx:
  stage: build
  tags: ["macosx"]
  extends: .only-master-mr
  script:
    - bash .gitlab/build.sh | tee ${LOGNAME}.log
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    expire_in: 180 minutes
    paths:
      - ${LOGNAME}.log
  cache:
    key: "${SYSTEM}-${VERSION}-$CI_COMMIT_REF_SLUG"
    untracked: true
    policy: push

build_seq_macosx:
  extends: .build_script_macosx
  variables:
    SYSTEM: macosx
    VERSION: seq
    LOGNAME: "pastix-build-${SYSTEM}-${VERSION}"

build_mpi_macosx:
  extends: .build_script_macosx
  variables:
    SYSTEM: macosx
    VERSION: mpi
    LOGNAME: "pastix-build-${SYSTEM}-${VERSION}"

.build_script_windows:
  stage: build
  tags: ['windows']
  extends: .only-master-mr
  script:
    - bash -lc .gitlab/build.sh | tee "$env:LOGNAME.log"
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    expire_in: 180 minutes
    paths:
      - ${LOGNAME}.log
  cache:
    key: "${SYSTEM}-${VERSION}-$CI_COMMIT_REF_SLUG"
    untracked: true
    policy: push

build_seq_windows:
  extends: .build_script_windows
  variables:
    SYSTEM: windows
    CHERE_INVOKING: "yes"
    MSYSTEM: UCRT64
    VERSION: seq
    LOGNAME: "pastix-build-${SYSTEM}-${VERSION}"
