#
# Default options for the gitlab CI test configurations
#
set( BUILD_SHARED_LIBS ON CACHE BOOL "" )

set( CMAKE_INSTALL_PREFIX "$ENV{PWD}/../install-${PASTIX_CI_VERSION}" CACHE PATH "" )
set( CMAKE_VERBOSE_MAKEFILE ON CACHE BOOL "" )
set( CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "" )

if ( (DEFINED PASTIX_CI_BRANCH) AND ("${PASTIX_CI_BRANCH}" STREQUAL "master") )
  set( CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "" FORCE )
else()
  set( CMAKE_BUILD_TYPE Debug CACHE STRING "" FORCE )
  set( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O0 -g" CACHE STRING "" )
endif()
set( PASTIX_COMPILE_OPTIONS "-Werror" )

set( PASTIX_ORDERING_SCOTCH   ON CACHE BOOL "" )
set( PASTIX_ORDERING_PTSCOTCH ON CACHE BOOL "" )
set( PASTIX_ORDERING_METIS    ON CACHE BOOL "" )

set( PASTIX_INT64 OFF CACHE BOOL "" )
set( PASTIX_LR_TESTINGS ON CACHE BOOL "" )

option(MORSE_ENABLE_WARNING  "Enable warning messages"        ON)
option(MORSE_ENABLE_COVERAGE "Enable flags for coverage test" ON)

# Enable the runtimes
set( PASTIX_WITH_STARPU ON CACHE BOOL "" )
set( PASTIX_WITH_PARSEC ON CACHE BOOL "" )

# Enable the Low-rank testings
set( PASTIX_LR_TESTINGS ON CACHE BOOL "" )

if ( "${PASTIX_CI_VERSION}" STREQUAL "doc" )
  set( BUILD_DOCUMENTATION ON CACHE BOOL "" )
  set( PASTIX_WITH_MPI     ON CACHE BOOL "" )
elseif ( "${PASTIX_CI_VERSION}" STREQUAL "mpi" )
  set( PASTIX_WITH_MPI ON  CACHE BOOL "" )
else()
  set( PASTIX_WITH_MPI OFF CACHE BOOL "" )
endif()
