FROM tthor/ci

USER root

# Installing as root: docker images are usually set up as root.
# Since some autotools scripts might complain about this being unsafe, we set
# FORCE_UNSAFE_CONFIGURE=1 to avoid configure errors.
ENV FORCE_UNSAFE_CONFIGURE=1
ENV DEBIAN_FRONTEND noninteractive

# Install common packages
RUN apt-get update && apt-get install -y \
  gnupg2 \
  libacl1-dev \
  libboost-dev \
  libboost-context-dev \
  libfftw3-dev \
  libfxt-dev \
  libgtg-dev \
  libhypre-dev \
  liblapack-dev \
  liblapacke-dev \
  libmetis-dev \
  libmumps-dev \
  libopenmpi-dev \
  libpapi-dev \
  libparmetis-dev \
  libpfm4-dev \
  libptscotch-dev \
  libscalapack-mpi-dev \
  libsuitesparse-dev \
  ocl-icd-opencl-dev \
  petsc-dev \
  slepc-dev \
  zlib1g-dev \
  python3-numpy \
  python3-mpi4py \
  python3-scipy && \
  apt-get autoremove -y

RUN apt-get autoremove -y
RUN apt-get autoclean -y
RUN apt-get purge -y

# For cppdiodon
RUN apt-get install -y libhdf5-mpi-dev

# change the default shell to be bash
SHELL ["/bin/bash", "-c"]

# Switch to gitlab user to install specific libraries in its home
USER gitlab

# Create directory where to install our specific libraries
RUN mkdir -p /home/gitlab/install

# Install QUARK
RUN cd $HOME && \
    git clone https://github.com/ecrc/quark && \
    cd quark/ && \
    sed -i -e "s#prefix=.*#prefix=/home/gitlab/install/quark#g" make.inc && \
    sed -i -e "s#CFLAGS=.*#CFLAGS= -g -O2 -DADD_ -fPIC#g" make.inc && \
    make && \
    make install && \
    cd $HOME && \
    rm quark/ -rf
ENV QUARK_DIR=/home/gitlab/install/quark

# Install PARSEC
RUN cd $HOME && \
    git clone https://bitbucket.org/mfaverge/parsec.git && \
    cd parsec && \
    git checkout mymaster && \
    git submodule update && \
    mkdir -p build-shm && \
    cd build-shm && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/home/gitlab/install/parsec-shm -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DPARSEC_GPU_WITH_CUDA=OFF && \
    make -j5 && \
    make install && \
    cd .. && \
    mkdir -p build-mpi && \
    cd build-mpi && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/home/gitlab/install/parsec-mpi -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DPARSEC_GPU_WITH_CUDA=OFF -DPARSEC_DIST_WITH_MPI=ON && \
    make -j5 && \
    make install && \
    cd $HOME && \
    rm parsec/ -rf
ENV PARSEC_DIR=/home/gitlab/install/parsec-shm
ENV PKG_CONFIG_PATH=$PARSEC_DIR/lib/pkgconfig:$PKG_CONFIG_PATH

# Install SimGrid
RUN cd $HOME && \
    wget https://framagit.org/simgrid/simgrid/uploads/b95690ca814bc12e905115e51e45112d/simgrid-3.27.tar.gz && \
    tar xvzf simgrid-3.27.tar.gz && \
    cd simgrid-3.27 && \
    cmake . -DCMAKE_INSTALL_PREFIX=/home/gitlab/install/simgrid -DCMAKE_BUILD_TYPE=Debug -Denable_msg=ON && \
    make -j5 && \
    make install && \
    cd $HOME && \
    rm simgrid-3.27/ simgrid-3.27.tar.gz -rf
ENV SIMGRID_DIR=/home/gitlab/install/simgrid
ENV PKG_CONFIG_PATH=$SIMGRID_DIR/lib/pkgconfig:$PKG_CONFIG_PATH

# Install StarPU
RUN cd $HOME && \
    wget https://files.inria.fr/starpu/starpu-1.3.9/starpu-1.3.9.tar.gz && \
    tar xvzf starpu-1.3.9.tar.gz && \
    cd starpu-1.3.9/ && \
    ./configure --prefix=/home/gitlab/install/starpu --enable-debug && \
    make -j5 && \
    make install && \
    export PKG_CONFIG_PATH=/home/gitlab/install/simgrid/lib/pkgconfig:$PKG_CONFIG_PATH && \
    ./configure --prefix=/home/gitlab/install/starpu-simgrid --enable-debug --disable-cuda --disable-opencl --with-fxt=/usr/lib/x86_64-linux-gnu/ --enable-simgrid --with-simgrid-dir=/home/gitlab/install/simgrid && \
    make -j5 && \
    make install && \
    cd $HOME && \
    rm starpu-1.3.9/ starpu-1.3.9.tar.gz -rf
ENV STARPU_DIR=/home/gitlab/install/starpu
ENV PKG_CONFIG_PATH=$STARPU_DIR/lib/pkgconfig:$PKG_CONFIG_PATH
ENV STARPUSIMGRID_DIR=/home/gitlab/install/starpu-simgrid

# Install Chameleon
RUN cd $HOME && \
    git clone --recursive https://gitlab.inria.fr/solverstack/chameleon.git && \
    cd chameleon/ && \
    source ./.gitlab-ci-env.sh && \
    mkdir build && \
    cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/home/gitlab/install/chameleon -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DCHAMELEON_USE_MPI=ON -DCHAMELEON_ENABLE_DOC=ON && \
    make -j5 && \
    make install && \
    cd $HOME && \
    rm chameleon/ -rf
ENV CHAMELEON_DIR=/home/gitlab/install/chameleon
ENV PKG_CONFIG_PATH=$CHAMELEON_DIR/lib/pkgconfig:$PKG_CONFIG_PATH

# Install HQR
RUN cd $HOME && \
    git clone --recursive https://gitlab.inria.fr/solverstack/hqr.git && \
    cd hqr/ && \
    mkdir build && \
    cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/home/gitlab/install/hqr -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON && \
    make -j5 && \
    make install && \
    cd $HOME && \
    rm hqr/ -rf
ENV HQR_DIR=/home/gitlab/install/hqr
ENV PKG_CONFIG_PATH=$HQR_DIR/lib/pkgconfig:$PKG_CONFIG_PATH

# Install Fabulous
RUN cd $HOME && \
    git clone --recursive -b develop https://gitlab.inria.fr/solverstack/fabulous.git && \
    cd fabulous/ && \
    mkdir build && \
    cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/home/gitlab/install/fabulous -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DFABULOUS_BUILD_C_API=ON -DFABULOUS_BUILD_Fortran_API=ON && \
    make -j5 && \
    make install && \
    cd $HOME && \
    rm fabulous/ -rf
ENV FABULOUS_DIR=/home/gitlab/install/fabulous
ENV PKG_CONFIG_PATH=$FABULOUS_DIR/lib/pkgconfig:$PKG_CONFIG_PATH

# Install SPM
RUN cd $HOME && \
    git clone --recursive https://gitlab.inria.fr/solverstack/spm.git && \
    cd spm/ && \
    mkdir build && \
    cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/home/gitlab/install/spm -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DSPM_INT64=OFF && \
    make -j5 && \
    make install && \
    cd $HOME && \
    rm spm/ -rf
ENV SPM_DIR=/home/gitlab/install/spm
ENV PKG_CONFIG_PATH=$SPM_DIR/lib/pkgconfig:$PKG_CONFIG_PATH

# Install PaStiX
RUN cd $HOME && \
    git clone --recursive https://gitlab.inria.fr/solverstack/pastix.git && \
    cd pastix/ && \
    mkdir build && \
    cd build && \
    PARSEC_DIR=/home/gitlab/install/parsec-shm && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/home/gitlab/install/pastix -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DPASTIX_WITH_STARPU=ON -DPASTIX_WITH_PARSEC=ON -DPASTIX_INT64=OFF && \
    make -j5 && \
    make install && \
    cd $HOME && \
    rm pastix/ -rf
ENV PASTIX_DIR=/home/gitlab/install/pastix
ENV PKG_CONFIG_PATH=$PASTIX_DIR/lib/pkgconfig:$PKG_CONFIG_PATH

# Set gitlab environment

# specific env. var.
ENV QUARK_DIR=/home/gitlab/install/quark
ENV PARSEC_DIR=/home/gitlab/install/parsec-shm
ENV STARPU_DIR=/home/gitlab/install/starpu
ENV SIMGRID_DIR=/home/gitlab/install/simgrid
ENV STARPUSIMGRID_DIR=/home/gitlab/install/starpu-simgrid
ENV CHAMELEON_DIR=/home/gitlab/install/chameleon
ENV HQR_DIR=/home/gitlab/install/hqr
ENV FABULOUS_DIR=/home/gitlab/install/fabulous
ENV SPM_DIR=/home/gitlab/install/spm
ENV PASTIX_DIR=/home/gitlab/install/pastix
WORKDIR /builds
