#ifdef PASTIX_DEBUG /* Select type of DEBUG */
/*
#define DEBUG_SOPALIN_ALLOC
#define DEBUG_SOPALIN_DIAG
#define DEBUG_SOPALIN_COMP_1D
#define DEBUG_SOPALIN_E1
#define DEBUG_SOPALIN_E2
#define DEBUG_SOPALIN_DRUNK
#define DEBUG_SOPALIN_RECV
#define DEBUG_SOPALIN_SEND
#define DEBUG_SOPALIN_INIT
#define DEBUG_SOPALIN_MAIN
#define DEBUG_SOPALIN_DOWN
#define DEBUG_SOPALIN_UP
#define DEBUG_SOPALIN_NAPA
*/
#endif
