###
#
# @file Makefile
#
#  PLASMA is a software package provided by Univ. of Tennessee,
#  Univ. of California Berkeley and Univ. of Colorado Denver
#
# @version 2.4.6
# @author Jakub Kurzak
# @date 2010-11-15
#
###

.PHONY: users_guide

all: users_guide

users_guide:
	( cd users_guide && $(MAKE) )

clean:
	rm -f ../pdf/users_guide.pdf
