PLASMA_INIT(INTEGER CORES, INTEGER INFO)

PLASMA_FINALIZE(INTEGER INFO)

PLASMA_ENABLE(INTEGER lever, INTEGER INFO)

PLASMA_DISABLE(INTEGER lever, INTEGER INFO)

PLASMA_SET(INTEGER param, INTEGER value, INTEGER INFO)

PLASMA_GET(INTEGER param, INTEGER value, INTEGER INFO)

PLASMA_DEALLOC_HANDLE(INTEGER sp, INTEGER INFO)

PLASMA_VERSION(INTEGER VER_MAJOR, INTEGER VER_MINOR, INTEGER VER_MICRO, INTEGER INFO)

PLASMA_DESC_CREATE(INTEGER*4 desc, INTEGER mat, INTEGER dtyp, INTEGER mb, INTEGER nb, INTEGER bsiz, INTEGER lm, INTEGER ln, INTEGER i, INTEGER j, INTEGER m, INTEGER n, INTEGER INFO)

PLASMA_DESC_DESTROY(INTEGER*4 desc, INTEGER INFO)

PLASMA_LAPACK_TO_TILE(INTEGER*4 Af77, INTEGER LDA, INTEGER*4 A, INTEGER INFO)

PLASMA_TILE_TO_LAPACK(INTEGER*4 A, INTEGER*4 Af77, INTEGER LDA, INTEGER INFO)
